services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/tododb
  
  db:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tododb
    volumes:
      - ./db_data:/var/lib/mysql

  dbtool:
    image: phpmyadmin:5-apache
    ports:
      - "80:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1